### ISSUE TITLE
Edit Breaking News Banner

### ISSUE THREAD

**Issue by sidlowsh** [Solomonabo/wp-content#2]
I love the breaking news banner! It really makes the site look like a legitimate news site. One comment: with the deep red background color and black font, the message is a little hard to read. Consider changing the text to white or the background color to a soft red to make it more legible.

**Comment by lexinal** [comment]
I also really like the breaking news banner. I feel like this made your website engage the user. I checked the banner on my mobile device and it works so that's good. However, I would definitely like to emphasize Sarah's comment because on the computer it was a little easier to read, but on my phone the colors clashed and it was difficult to read the itty bitty banner.

**Comment by Solomonabo** [comment]
Great feedback guys, I don't even know why I used the red, will modify it. 
Thanks so much
